language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.12"
  - "7.10"
  - "8.9"
  - "9.2"
matrix:
  fast_finish: true
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  # - "npm config set shrinkwrap false"

  # # Setup Node.js version-specific dependencies
  # - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"
  # # Update Node.js modules
  # - "test ! -d node_modules || npm prune"
  # - "test ! -d node_modules || npm rebuild"
script:
  - "npm run test"
after_success: npm run coverage


